// Application constants
export const ROLES = {
  STUDENT: 'STUDENT',
  MANAGER: 'MANAGER',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN'
};

export const FUNDING_TYPES = {
  FULLY_FUNDED: 'FULLY_FUNDED',
  PARTIALLY_FUNDED: 'PARTIALLY_FUNDED',
  SELF_FUNDED: 'SELF_FUNDED'
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  EXPIRED: 'EXPIRED'
};

export const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  BOOKMARKED: 'BOOKMARKED',
  APPLIED: 'APPLIED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
};

export const DOCUMENT_TYPES = {
  CV: 'CV',
  COVER_LETTER: 'COVER_LETTER',
  PERSONAL_STATEMENT: 'PERSONAL_STATEMENT',
  OTHER: 'OTHER'
};

// JWT token expiration
export const JWT_EXPIRATION = {
  ACCESS_TOKEN: '24h',
  REFRESH_TOKEN: '7d'
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};

